export interface Stage {
  id: string
  number: number
  title: string
  goal: string
  explanation: string
  checklist: string[]
  questions: string[]
  whyThisMatters: string
  commonMistakes: string[]
  reviewerWarning: string
  requiredOutput: string
}

export const stages: Stage[] = [
  {
    id: "project-setup",
    number: 0,
    title: "Project Setup",
    goal: "Define the research project container.",
    explanation:
      "Before research begins, define what the project is, what field it belongs to, and what output is expected.",
    checklist: [
      "Title entered",
      "Domain selected",
      "Research type selected",
      "Target venue entered",
      "Expected output selected",
    ],
    questions: [
      "What is the working title?",
      "What field or domain does this belong to?",
      "What is the target venue or audience?",
      "Is this theoretical, empirical, engineering, evaluation, survey, or design research?",
      "What is the expected output: paper, poster, prototype, dataset, benchmark, or proposal?",
    ],
    whyThisMatters: "Weak setup creates vague research direction.",
    commonMistakes: [
      "Starting with a paper title before defining the research problem",
      "Choosing a venue too late",
      "Mixing multiple unrelated research types",
    ],
    reviewerWarning: "A vague project setup causes vague research.",
    requiredOutput: "A clearly defined project identity.",
  },
  {
    id: "understand-the-field",
    number: 1,
    title: "Understand the Field",
    goal: "Build enough context to avoid naïve or already-solved ideas.",
    explanation: "You must understand the field before claiming novelty.",
    checklist: [
      "List 5–10 foundational papers",
      "List 5–10 recent papers",
      "List top venues",
      "List major datasets/tools",
      "Write a one-paragraph field summary",
    ],
    questions: [
      "What field are you working in?",
      "What are the major venues?",
      "What are the major datasets, tools, or benchmarks?",
      "What are the key terms and concepts?",
      "What do experts currently care about?",
    ],
    whyThisMatters: "Research without field understanding usually reinvents existing work.",
    commonMistakes: [
      "Proposing novelty too early",
      "Reading only recent papers",
      "Ignoring benchmarks and datasets",
    ],
    reviewerWarning: "Do not propose novelty before proving you understand the field.",
    requiredOutput: "A concise field map.",
  },
  {
    id: "observation",
    number: 2,
    title: "Observation",
    goal: "Identify something strange, inefficient, missing, weak, or underexplored.",
    explanation: "Research begins from an observation, not from a desire to write a paper.",
    checklist: [
      "Observation written",
      "Example or evidence recorded",
      "Importance explained",
      "Affected stakeholders identified",
    ],
    questions: [
      "What seems broken, strange, missing, or inefficient?",
      "Where did you notice this?",
      "Why is it surprising?",
      "Who is affected?",
      "What early evidence supports this observation?",
    ],
    whyThisMatters: "The observation is the seed of the research problem.",
    commonMistakes: [
      "Confusing personal interest with research significance",
      "Treating a tool idea as a research idea",
      "Having no evidence for the observation",
    ],
    reviewerWarning: "An observation is not a contribution yet.",
    requiredOutput: "A specific observation with early evidence.",
  },
  {
    id: "problem-statement",
    number: 3,
    title: "Problem Statement",
    goal: "Convert the observation into a precise research problem.",
    explanation: "The problem statement defines what the research is actually trying to solve.",
    checklist: [
      "One-sentence problem statement written",
      "Scope defined",
      "Out-of-scope items defined",
      "Importance justified",
    ],
    questions: [
      "What exactly is the problem?",
      "What is the boundary of the problem?",
      "What is out of scope?",
      "Why does the problem matter scientifically or practically?",
      "What happens if nobody solves it?",
    ],
    whyThisMatters: "A broad problem cannot produce a strong paper.",
    commonMistakes: [
      "Writing a mission statement instead of a research problem",
      "Using vague words like better, robust, efficient without definition",
      "Not defining scope",
    ],
    reviewerWarning: "A broad problem cannot produce a strong paper.",
    requiredOutput: "A precise, bounded problem statement.",
  },
  {
    id: "literature-review",
    number: 4,
    title: "Literature Review",
    goal: "Find what already exists and avoid reinventing old work.",
    explanation: "Literature review determines whether the idea is actually new.",
    checklist: [
      "At least 10 relevant papers added",
      "Each paper summarized",
      "Methods extracted",
      "Datasets extracted",
      "Metrics extracted",
      "Limitations extracted",
    ],
    questions: [
      "Which papers are closest to your idea?",
      "What methods do they use?",
      "What datasets do they use?",
      "What metrics do they report?",
      "What limitations do they admit?",
      "What limitations do you see?",
    ],
    whyThisMatters: "Without literature review, novelty claims are weak.",
    commonMistakes: [
      "Cherry-picking only supportive papers",
      "Ignoring closest competitors",
      "Relying on low-quality or unverified sources",
    ],
    reviewerWarning: "If you cannot name the closest competing paper, you do not know the gap yet.",
    requiredOutput: "A structured map of existing work.",
  },
  {
    id: "gap-analysis",
    number: 5,
    title: "Gap Analysis",
    goal: "Identify what current work does not do.",
    explanation: "The gap is the missing piece your research targets.",
    checklist: [
      "Existing work summarized",
      "Missing piece identified",
      "Importance explained",
      "Testability confirmed",
      "Closest competing paper identified",
    ],
    questions: [
      "What does existing work already solve?",
      "What does existing work fail to address?",
      "Is the gap important or just convenient?",
      "Why has the gap not been solved?",
      "Is the gap testable?",
    ],
    whyThisMatters: "A weak gap leads to a weak contribution.",
    commonMistakes: [
      "Claiming “nobody used method X on dataset Y” as novelty without deeper reason",
      "Choosing a gap only because it is easy",
      "Not proving the gap exists",
    ],
    reviewerWarning: "“Nobody used method X on dataset Y” is usually a weak gap unless the reason matters.",
    requiredOutput: "A defensible, testable research gap.",
  },
  {
    id: "research-question",
    number: 6,
    title: "Research Question",
    goal: "Create a specific, measurable, answerable question.",
    explanation: "The research question controls the study design.",
    checklist: [
      "Primary RQ written",
      "Secondary RQs written if needed",
      "Measurability confirmed",
      "Falsifiability confirmed",
    ],
    questions: [
      "What is your primary research question?",
      "What are your secondary research questions?",
      "What would count as an answer?",
      "What would falsify your assumption?",
      "Is the question narrow enough for one paper?",
    ],
    whyThisMatters: "A research question must be answerable with evidence.",
    commonMistakes: [
      "Asking questions too broad for one paper",
      "Asking questions that cannot be measured",
      "Hiding claims inside vague wording",
    ],
    reviewerWarning: "A research question must be answerable with evidence.",
    requiredOutput: "One clear primary research question.",
  },
  {
    id: "hypothesis",
    number: 7,
    title: "Hypothesis",
    goal: "State what you expect before experiments.",
    explanation: "The hypothesis states your prediction before observing results.",
    checklist: [
      "H1 written",
      "Null or alternative hypothesis written",
      "Expected direction defined",
      "Rejection criteria defined",
    ],
    questions: [
      "What do you predict will happen?",
      "Why do you expect that?",
      "What evidence would support the hypothesis?",
      "What evidence would reject it?",
      "What result would be inconclusive?",
    ],
    whyThisMatters: "A hypothesis disciplines interpretation.",
    commonMistakes: [
      "Writing the hypothesis after seeing results",
      "Making unfalsifiable predictions",
      "Confusing hypothesis with conclusion",
    ],
    reviewerWarning: "A hypothesis written after seeing results is weak research practice.",
    requiredOutput: "A falsifiable hypothesis.",
  },
  {
    id: "research-design",
    number: 8,
    title: "Research Design",
    goal: "",
    explanation: "",
    checklist: [],
    questions: [],
    whyThisMatters: "",
    commonMistakes: [],
    reviewerWarning: "",
    requiredOutput: "",
  },
  {
    id: "data-collection",
    number: 9,
    title: "Data Collection / Setup",
    goal: "",
    explanation: "",
    checklist: [],
    questions: [],
    whyThisMatters: "",
    commonMistakes: [],
    reviewerWarning: "",
    requiredOutput: "",
  },
  {
    id: "method-implementation",
    number: 10,
    title: "Method / Implementation",
    goal: "",
    explanation: "",
    checklist: [],
    questions: [],
    whyThisMatters: "",
    commonMistakes: [],
    reviewerWarning: "",
    requiredOutput: "",
  },
  {
    id: "experiments",
    number: 11,
    title: "Experiments",
    goal: "",
    explanation: "",
    checklist: [],
    questions: [],
    whyThisMatters: "",
    commonMistakes: [],
    reviewerWarning: "",
    requiredOutput: "",
  },
  {
    id: "statistical-validation",
    number: 12,
    title: "Statistical Validation",
    goal: "",
    explanation: "",
    checklist: [],
    questions: [],
    whyThisMatters: "",
    commonMistakes: [],
    reviewerWarning: "",
    requiredOutput: "",
  },
  {
    id: "result-analysis",
    number: 13,
    title: "Result Analysis",
    goal: "",
    explanation: "",
    checklist: [],
    questions: [],
    whyThisMatters: "",
    commonMistakes: [],
    reviewerWarning: "",
    requiredOutput: "",
  },
  {
    id: "threats-to-validity",
    number: 14,
    title: "Threats to Validity",
    goal: "",
    explanation: "",
    checklist: [],
    questions: [],
    whyThisMatters: "",
    commonMistakes: [],
    reviewerWarning: "",
    requiredOutput: "",
  },
  {
    id: "contributions",
    number: 15,
    title: "Contributions",
    goal: "",
    explanation: "",
    checklist: [],
    questions: [],
    whyThisMatters: "",
    commonMistakes: [],
    reviewerWarning: "",
    requiredOutput: "",
  },
  {
    id: "paper-outline",
    number: 16,
    title: "Paper Outline",
    goal: "",
    explanation: "",
    checklist: [],
    questions: [],
    whyThisMatters: "",
    commonMistakes: [],
    reviewerWarning: "",
    requiredOutput: "",
  },
  {
    id: "internal-review",
    number: 17,
    title: "Internal Review",
    goal: "",
    explanation: "",
    checklist: [],
    questions: [],
    whyThisMatters: "",
    commonMistakes: [],
    reviewerWarning: "",
    requiredOutput: "",
  },
  {
    id: "submission-planning",
    number: 18,
    title: "Submission Planning",
    goal: "",
    explanation: "",
    checklist: [],
    questions: [],
    whyThisMatters: "",
    commonMistakes: [],
    reviewerWarning: "",
    requiredOutput: "",
  },
  {
    id: "peer-review-tracking",
    number: 19,
    title: "Peer Review Tracking",
    goal: "",
    explanation: "",
    checklist: [],
    questions: [],
    whyThisMatters: "",
    commonMistakes: [],
    reviewerWarning: "",
    requiredOutput: "",
  },
  {
    id: "revision",
    number: 20,
    title: "Revision",
    goal: "",
    explanation: "",
    checklist: [],
    questions: [],
    whyThisMatters: "",
    commonMistakes: [],
    reviewerWarning: "",
    requiredOutput: "",
  },
  {
    id: "publication-extension",
    number: 21,
    title: "Publication and Extension",
    goal: "",
    explanation: "",
    checklist: [],
    questions: [],
    whyThisMatters: "",
    commonMistakes: [],
    reviewerWarning: "",
    requiredOutput: "",
  },
]
