export interface Stage {
  id: string
  number: number
  title: string
  goal: string
  explanation: string
  checklist: string[]
  questions: string[]
  whyThisMatters: string
  commonMistakes: string[]
  reviewerWarning: string
  requiredOutput: string
}

export const stages: Stage[] = [
  {
    id: "project-setup",
    number: 0,
    title: "Project Setup",
    goal: "Define the research project container.",
    explanation:
      "Before research begins, define what the project is, what field it belongs to, and what output is expected.",
    checklist: [
      "Title entered",
      "Domain selected",
      "Research type selected",
      "Target venue entered",
      "Expected output selected",
    ],
    questions: [
      "What is the working title?",
      "What field or domain does this belong to?",
      "What is the target venue or audience?",
      "Is this theoretical, empirical, engineering, evaluation, survey, or design research?",
      "What is the expected output: paper, poster, prototype, dataset, benchmark, or proposal?",
    ],
    whyThisMatters: "Weak setup creates vague research direction.",
    commonMistakes: [
      "Starting with a paper title before defining the research problem",
      "Choosing a venue too late",
      "Mixing multiple unrelated research types",
    ],
    reviewerWarning: "A vague project setup causes vague research.",
    requiredOutput: "A clearly defined project identity.",
  },
  {
    id: "understand-the-field",
    number: 1,
    title: "Understand the Field",
    goal: "Build enough context to avoid naïve or already-solved ideas.",
    explanation: "You must understand the field before claiming novelty.",
    checklist: [
      "List 5–10 foundational papers",
      "List 5–10 recent papers",
      "List top venues",
      "List major datasets/tools",
      "Write a one-paragraph field summary",
    ],
    questions: [
      "What field are you working in?",
      "What are the major venues?",
      "What are the major datasets, tools, or benchmarks?",
      "What are the key terms and concepts?",
      "What do experts currently care about?",
    ],
    whyThisMatters: "Research without field understanding usually reinvents existing work.",
    commonMistakes: [
      "Proposing novelty too early",
      "Reading only recent papers",
      "Ignoring benchmarks and datasets",
    ],
    reviewerWarning: "Do not propose novelty before proving you understand the field.",
    requiredOutput: "A concise field map.",
  },
  {
    id: "observation",
    number: 2,
    title: "Observation",
    goal: "Identify something strange, inefficient, missing, weak, or underexplored.",
    explanation: "Research begins from an observation, not from a desire to write a paper.",
    checklist: [
      "Observation written",
      "Example or evidence recorded",
      "Importance explained",
      "Affected stakeholders identified",
    ],
    questions: [
      "What seems broken, strange, missing, or inefficient?",
      "Where did you notice this?",
      "Why is it surprising?",
      "Who is affected?",
      "What early evidence supports this observation?",
    ],
    whyThisMatters: "The observation is the seed of the research problem.",
    commonMistakes: [
      "Confusing personal interest with research significance",
      "Treating a tool idea as a research idea",
      "Having no evidence for the observation",
    ],
    reviewerWarning: "An observation is not a contribution yet.",
    requiredOutput: "A specific observation with early evidence.",
  },
  {
    id: "problem-statement",
    number: 3,
    title: "Problem Statement",
    goal: "Convert the observation into a precise research problem.",
    explanation: "The problem statement defines what the research is actually trying to solve.",
    checklist: [
      "One-sentence problem statement written",
      "Scope defined",
      "Out-of-scope items defined",
      "Importance justified",
    ],
    questions: [
      "What exactly is the problem?",
      "What is the boundary of the problem?",
      "What is out of scope?",
      "Why does the problem matter scientifically or practically?",
      "What happens if nobody solves it?",
    ],
    whyThisMatters: "A broad problem cannot produce a strong paper.",
    commonMistakes: [
      "Writing a mission statement instead of a research problem",
      "Using vague words like better, robust, efficient without definition",
      "Not defining scope",
    ],
    reviewerWarning: "A broad problem cannot produce a strong paper.",
    requiredOutput: "A precise, bounded problem statement.",
  },
  {
    id: "literature-review",
    number: 4,
    title: "Literature Review",
    goal: "Find what already exists and avoid reinventing old work.",
    explanation: "Literature review determines whether the idea is actually new.",
    checklist: [
      "At least 10 relevant papers added",
      "Each paper summarized",
      "Methods extracted",
      "Datasets extracted",
      "Metrics extracted",
      "Limitations extracted",
    ],
    questions: [
      "Which papers are closest to your idea?",
      "What methods do they use?",
      "What datasets do they use?",
      "What metrics do they report?",
      "What limitations do they admit?",
      "What limitations do you see?",
    ],
    whyThisMatters: "Without literature review, novelty claims are weak.",
    commonMistakes: [
      "Cherry-picking only supportive papers",
      "Ignoring closest competitors",
      "Relying on low-quality or unverified sources",
    ],
    reviewerWarning: "If you cannot name the closest competing paper, you do not know the gap yet.",
    requiredOutput: "A structured map of existing work.",
  },
  {
    id: "gap-analysis",
    number: 5,
    title: "Gap Analysis",
    goal: "Identify what current work does not do.",
    explanation: "The gap is the missing piece your research targets.",
    checklist: [
      "Existing work summarized",
      "Missing piece identified",
      "Importance explained",
      "Testability confirmed",
      "Closest competing paper identified",
    ],
    questions: [
      "What does existing work already solve?",
      "What does existing work fail to address?",
      "Is the gap important or just convenient?",
      "Why has the gap not been solved?",
      "Is the gap testable?",
    ],
    whyThisMatters: "A weak gap leads to a weak contribution.",
    commonMistakes: [
      "Claiming “nobody used method X on dataset Y” as novelty without deeper reason",
      "Choosing a gap only because it is easy",
      "Not proving the gap exists",
    ],
    reviewerWarning: "“Nobody used method X on dataset Y” is usually a weak gap unless the reason matters.",
    requiredOutput: "A defensible, testable research gap.",
  },
  {
    id: "research-question",
    number: 6,
    title: "Research Question",
    goal: "Create a specific, measurable, answerable question.",
    explanation: "The research question controls the study design.",
    checklist: [
      "Primary RQ written",
      "Secondary RQs written if needed",
      "Measurability confirmed",
      "Falsifiability confirmed",
    ],
    questions: [
      "What is your primary research question?",
      "What are your secondary research questions?",
      "What would count as an answer?",
      "What would falsify your assumption?",
      "Is the question narrow enough for one paper?",
    ],
    whyThisMatters: "A research question must be answerable with evidence.",
    commonMistakes: [
      "Asking questions too broad for one paper",
      "Asking questions that cannot be measured",
      "Hiding claims inside vague wording",
    ],
    reviewerWarning: "A research question must be answerable with evidence.",
    requiredOutput: "One clear primary research question.",
  },
  {
    id: "hypothesis",
    number: 7,
    title: "Hypothesis",
    goal: "State what you expect before experiments.",
    explanation: "The hypothesis states your prediction before observing results.",
    checklist: [
      "H1 written",
      "Null or alternative hypothesis written",
      "Expected direction defined",
      "Rejection criteria defined",
    ],
    questions: [
      "What do you predict will happen?",
      "Why do you expect that?",
      "What evidence would support the hypothesis?",
      "What evidence would reject it?",
      "What result would be inconclusive?",
    ],
    whyThisMatters: "A hypothesis disciplines interpretation.",
    commonMistakes: [
      "Writing the hypothesis after seeing results",
      "Making unfalsifiable predictions",
      "Confusing hypothesis with conclusion",
    ],
    reviewerWarning: "A hypothesis written after seeing results is weak research practice.",
    requiredOutput: "A falsifiable hypothesis.",
  },
  {
    id: "research-design",
    number: 8,
    title: "Research Design",
    goal: "Design the study that would convince a skeptical reviewer.",
    explanation: "This stage defines the evidence needed to support or reject the research hypothesis.",
    checklist: [
      "Dataset/source selected",
      "Baselines selected",
      "Metrics selected",
      "Experimental protocol written",
      "Success/failure criteria defined",
      "Reproducibility plan written",
    ],
    questions: [
      "What data will you use?",
      "What baselines will you compare against?",
      "What metrics will you report?",
      "What is the main experiment?",
      "What ablations or sensitivity tests are needed?",
      "What would convince a skeptical reviewer?",
    ],
    whyThisMatters: "Good research design prevents weak evidence and post-hoc reasoning.",
    commonMistakes: [
      "Choosing baselines after results",
      "Using metrics that do not match the claim",
      "Designing experiments around convenience",
    ],
    reviewerWarning: "Design the experiment before touching results.",
    requiredOutput: "A complete experimental protocol.",
  },
  {
    id: "data-collection",
    number: 9,
    title: "Data Collection / Setup",
    goal: "Prepare all evidence sources before analysis.",
    explanation: "Data provenance and preprocessing must be clear before experiments begin.",
    checklist: [
      "Data acquired",
      "Source documented",
      "License/ethics checked",
      "Preprocessing documented",
      "Data quality issues recorded",
    ],
    questions: [
      "Where does the data come from?",
      "Is the data legally and ethically usable?",
      "What preprocessing is needed?",
      "What quality problems exist?",
      "What assumptions are being made?",
    ],
    whyThisMatters: "Unclear data provenance damages credibility.",
    commonMistakes: ["Not documenting preprocessing", "Ignoring licensing constraints", "Assuming clean data"],
    reviewerWarning: "Unclear data provenance can kill the credibility of the paper.",
    requiredOutput: "Documented data source and preprocessing plan.",
  },
  {
    id: "method-implementation",
    number: 10,
    title: "Method / Implementation",
    goal: "Build the model, algorithm, metric, framework, simulation, or tool.",
    explanation: "This stage converts the research design into a reproducible method.",
    checklist: [
      "Method implemented",
      "Code organized",
      "Configuration tracked",
      "Small test run completed",
      "Outputs saved systematically",
    ],
    questions: [
      "What exactly are you building?",
      "What are the inputs?",
      "What are the outputs?",
      "What are the key design decisions?",
      "How will someone reproduce it?",
      "What could silently break?",
    ],
    whyThisMatters: "A method must be reproducible and tied to the research question.",
    commonMistakes: ["Treating a demo as evidence", "Not tracking configs", "Hiding implementation assumptions"],
    reviewerWarning: "A working demo is not automatically a research contribution.",
    requiredOutput: "Reproducible implementation or method description.",
  },
  {
    id: "experiments",
    number: 11,
    title: "Experiments",
    goal: "Run main experiments, baselines, ablations, and failure checks.",
    explanation: "Experiments produce the evidence for the paper.",
    checklist: [
      "Main experiment completed",
      "Baselines completed",
      "Ablation study completed",
      "Sensitivity analysis completed",
      "Failure cases collected",
      "Results table created",
    ],
    questions: [
      "What is the main result?",
      "How does it compare to baselines?",
      "Which part of the method matters most?",
      "Where does it fail?",
      "Are results stable across runs?",
    ],
    whyThisMatters: "Strong experiments separate research from speculation.",
    commonMistakes: ["Reporting only successful cases", "No baseline", "No failure analysis"],
    reviewerWarning: "A result without baselines is usually not convincing.",
    requiredOutput: "Results table with baseline comparison.",
  },
  {
    id: "statistical-validation",
    number: 12,
    title: "Statistical Validation",
    goal: "Check whether results are reliable or noise.",
    explanation: "This stage evaluates whether results are stable and meaningful.",
    checklist: [
      "Variance reported",
      "Confidence intervals or equivalent uncertainty calculated where appropriate",
      "Multiple runs completed if applicable",
      "Effect size discussed",
      "Honest uncertainty written",
    ],
    questions: [
      "Are the results stable?",
      "Could the result be random?",
      "How large is the effect?",
      "What uncertainty should be reported?",
      "Are confidence intervals or significance tests needed?",
    ],
    whyThisMatters: "Reviewers need to know whether effects are real.",
    commonMistakes: [
      "Calling a result significant without statistical support",
      "Reporting one lucky run",
      "Ignoring variance",
    ],
    reviewerWarning: "Do not call something significant unless you have evidence.",
    requiredOutput: "Stability or uncertainty analysis.",
  },
  {
    id: "result-analysis",
    number: 13,
    title: "Result Analysis",
    goal: "Explain why the result happened, not just what happened.",
    explanation: "Analysis turns results into insight.",
    checklist: [
      "Main findings summarized",
      "Mechanism explained",
      "Prior work comparison written",
      "Unexpected results documented",
    ],
    questions: [
      "What did you learn?",
      "Why did the result happen?",
      "What confirms your hypothesis?",
      "What contradicts your hypothesis?",
      "How does this compare with prior work?",
      "What surprised you?",
    ],
    whyThisMatters: "Results are weaker without interpretation.",
    commonMistakes: ["Only listing numbers", "Ignoring contradiction", "Not comparing with prior work"],
    reviewerWarning: "Results are weaker without interpretation.",
    requiredOutput: "Interpretation of findings.",
  },
  {
    id: "threats-to-validity",
    number: 14,
    title: "Threats to Validity",
    goal: "Attack your own work before reviewers do.",
    explanation: "This stage documents weaknesses honestly and professionally.",
    checklist: [
      "Internal validity threats listed",
      "External validity threats listed",
      "Construct validity threats listed",
      "Statistical validity threats listed",
      "Mitigations written",
    ],
    questions: [
      "What could be wrong with the experiment?",
      "What limits generalization?",
      "Are your metrics measuring the right thing?",
      "What assumptions could fail?",
      "What would a harsh reviewer attack?",
    ],
    whyThisMatters: "Controlled honesty increases credibility.",
    commonMistakes: ["Hiding weaknesses", "Writing generic limitations", "Ignoring metric validity"],
    reviewerWarning: "Controlled honesty increases credibility. Hidden weaknesses look worse.",
    requiredOutput: "Validity threats and mitigations.",
  },
  {
    id: "contributions",
    number: 15,
    title: "Contributions",
    goal: "Extract the real novelty and avoid overclaiming.",
    explanation: "Contributions should be supported directly by evidence.",
    checklist: [
      "1-3 contributions written",
      "Evidence mapped to each contribution",
      "Weak claims removed",
      "Contribution wording made defensible",
    ],
    questions: [
      "What is actually new?",
      "What evidence supports each contribution?",
      "Which contribution is strongest?",
      "Which claim is weakest?",
      "Are you claiming more than you proved?",
    ],
    whyThisMatters: "Contributions define why the paper deserves acceptance.",
    commonMistakes: [
      "Listing implementation details as contributions",
      "Claiming too much",
      "Having more than three contributions",
    ],
    reviewerWarning: "Implementation details are not automatically contributions.",
    requiredOutput: "1-3 defensible contributions.",
  },
  {
    id: "paper-outline",
    number: 16,
    title: "Paper Outline",
    goal: "Convert evidence into a clear paper structure.",
    explanation: "The paper outline should follow the evidence collected so far.",
    checklist: [
      "Full outline created",
      "Section goals defined",
      "Figures/tables planned",
      "Claims aligned with evidence",
    ],
    questions: [
      "What is the core story?",
      "What should the abstract promise?",
      "What belongs in the introduction?",
      "What belongs in the results?",
      "What belongs in limitations?",
    ],
    whyThisMatters: "Structure determines whether reviewers understand the work.",
    commonMistakes: ["Writing before evidence is ready", "Overloading introduction", "Hiding limitations"],
    reviewerWarning: "A paper outline should follow evidence, not ambition.",
    requiredOutput: "Paper outline with section goals.",
  },
  {
    id: "internal-review",
    number: 17,
    title: "Internal Review",
    goal: "Reject your own paper before external reviewers do.",
    explanation: "This stage identifies weaknesses before submission.",
    checklist: [
      "Novelty checked",
      "Evidence checked",
      "Reproducibility checked",
      "Claim discipline checked",
      "Weak sections identified",
    ],
    questions: [
      "Why would this paper be rejected?",
      "Which claim is weakest?",
      "Which experiment is missing?",
      "Is the novelty clear?",
      "Is the work reproducible?",
      "Is the paper overselling?",
    ],
    whyThisMatters: "Self-review improves acceptance odds.",
    commonMistakes: [
      "Only proofreading instead of reviewing substance",
      "Ignoring missing baselines",
      "Not checking claim strength",
    ],
    reviewerWarning: "If you cannot identify weaknesses, reviewers will.",
    requiredOutput: "Internal rejection memo and fixes.",
  },
  {
    id: "submission-planning",
    number: 18,
    title: "Submission Planning",
    goal: "Prepare for correct venue submission.",
    explanation: "Venue fit and formatting matter.",
    checklist: [
      "Venue selected",
      "Deadline entered",
      "Formatting checked",
      "Anonymity checked",
      "Required files listed",
    ],
    questions: [
      "Which venue is best?",
      "Why does this venue fit?",
      "What is the deadline?",
      "What are the formatting rules?",
      "What are the anonymity rules?",
      "What files are required?",
    ],
    whyThisMatters: "Good research can fail from poor venue fit.",
    commonMistakes: ["Choosing venue after writing", "Ignoring page limits", "Violating anonymity rules"],
    reviewerWarning: "Good research can still fail from poor venue fit.",
    requiredOutput: "Submission checklist.",
  },
  {
    id: "peer-review-tracking",
    number: 19,
    title: "Peer Review Tracking",
    goal: "Track reviewer feedback and response strategy.",
    explanation: "Reviews should be categorized into valid criticism, fixable issues, and strategic disagreements.",
    checklist: ["Reviews entered", "Criticisms categorized", "Required fixes listed", "Response plan written"],
    questions: [
      "What are the main reviewer objections?",
      "Which objections are valid?",
      "What can be fixed?",
      "What cannot be fixed without new research?",
      "What is the resubmission strategy?",
    ],
    whyThisMatters: "Review response requires discipline, not emotion.",
    commonMistakes: [
      "Treating all reviewer comments equally",
      "Becoming defensive",
      "Fixing wording while ignoring substance",
    ],
    reviewerWarning: "Do not treat every reviewer comment equally. Classify them.",
    requiredOutput: "Review response strategy.",
  },
  {
    id: "revision",
    number: 20,
    title: "Revision",
    goal: "Improve the work based on review or self-review.",
    explanation: "Revision should improve truthfulness, evidence, and clarity.",
    checklist: [
      "Experiments revised",
      "Framing revised",
      "Claims revised",
      "Limitations revised",
      "Response written if needed",
    ],
    questions: [
      "What changed after review?",
      "Which claim was weakened?",
      "Which claim was strengthened?",
      "What new evidence was added?",
      "Is the revised version more defensible?",
    ],
    whyThisMatters: "Good revision strengthens the research, not just the writing.",
    commonMistakes: [
      "Only polishing text",
      "Ignoring core reviewer concerns",
      "Strengthening claims without new evidence",
    ],
    reviewerWarning: "Revision should improve truthfulness, not just persuasion.",
    requiredOutput: "Revised research package.",
  },
  {
    id: "publication-extension",
    number: 21,
    title: "Publication and Extension",
    goal: "Release the work and define the next research step.",
    explanation: "Research should become a program, not a one-off artifact.",
    checklist: [
      "Paper archived",
      "Code/data released if possible",
      "Presentation prepared",
      "Lessons learned documented",
      "Next research direction defined",
    ],
    questions: [
      "What will be released?",
      "How can others reproduce it?",
      "What is the next extension?",
      "What research program does this become?",
      "What should the next paper be?",
    ],
    whyThisMatters: "Publication is not the end of research.",
    commonMistakes: [
      "Stopping after acceptance",
      "Not releasing reproducibility artifacts",
      "Failing to define next steps",
    ],
    reviewerWarning: "One paper is not a research program. Define the next step.",
    requiredOutput: "Publication and extension plan.",
  },
]
